Feat/connexion to templates
Nathan-Etave/PinPon45 pull request #23
Opened 2023-11-07 14:31 UTC by ArthurVillette

création de la page de conneXion:
-ficher conneXion css (visuel)
-fichier conneXion HTML (le squellette)

2023-11-07 14:43 UTC, Nathan-Etave requested changes

2023-11-07 14:43 UTC, Nathan-Etave commented on app/templates/connexion.html
> +                <form method:"POST" class="page_connexion" action="connexion">
:-1: Pas de ':'

2023-11-07 14:43 UTC, Norikokonut approved these changes

2023-11-07 14:47 UTC, Nathan-Etave requested changes
Il manque également les formulaires WTForms pour le Flask

2023-11-07 15:32 UTC, ArthurVillette commented
correction effectuer

2023-11-08 08:33 UTC, LouisL18 approved these changes
ok pour moi

2023-11-08 09:02 UTC, Nathan-Etave requested changes

2023-11-08 09:02 UTC, Nathan-Etave commented on app/templates/connexion.html
> +            <link rel="stylesheet" href="{{ url_for('static',filename='css/bottomHeader.css')}}">
Il manque le CSS pour le @media du bottomHeader. ಠ_ಠ

2023-11-08 09:03 UTC, ArthurVillette commented
ajustement effectuer

2023-11-08 09:11 UTC, Nathan-Etave requested changes

2023-11-08 09:11 UTC, Nathan-Etave commented on app/static/css/connexion.css
> +    margin-top: 8rem;
8 rem c'est beaucoup trop, 2rem c'est mieux.

2023-11-08 09:11 UTC, Nathan-Etave commented on app/static/css/connexion.css
> +        width: 50%;
Le width doit être de 75%!

2023-11-08 09:11 UTC, Nathan-Etave commented on app/static/css/connexion.css
> +            width: 30%;
Le width doit être de 75%!

2023-11-08 09:15 UTC, ArthurVillette commented
changement effectuer CHEF

2023-11-08 12:34 UTC, Nathan-Etave reviewed
C'est finalement bon pour moi.

2023-11-08 12:58 UTC, Nathan-Etave approved these changes
C'est finalement bon pour moi.

2023-11-08 12:59 UTC, Norikokonut approved these changes
lgtm

2023-11-08 13:02 UTC, RomainMechain approved these changes
Après les modifications, les fichiers sont correcte je valide.

2023-11-08 13:27 UTC, merged