Ajout de Feature/user
Nathan-Etave/PinPon45 pull request #25
Opened 2023-11-08 08:32 UTC by LouisL18

Merge de la branche Feature/user dans la branche feature/template. Cela contient le html des pages user et edit_user ainsi que leur css.

2023-11-08 08:35 UTC, ArthurVillette approved these changes
ok pour moi

2023-11-08 09:23 UTC, Nathan-Etave commented on app/static/css/user.css
Il manque tout les @media qui permettent l'affichage sur mobile. ಠ_ಠ

2023-11-08 15:57 UTC, ArthurVillette approved these changes
ok pour moiccfdcvd

2023-11-09 09:18 UTC, Norikokonut requested changes

2023-11-09 09:18 UTC, Norikokonut commented on app/templates/user.html
> +                <p>{{ user.nom }} : {{ user.nom }}</p>
Pourquoi pas 
<p>Nom : {{ user.nom }}</p> 
??

2023-11-09 09:21 UTC, Norikokonut requested changes

2023-11-09 09:21 UTC, Norikokonut commented on app/templates/baseUser.html
Fichier en camelCase au lieu de snake_case

2023-11-09 09:33 UTC, LouisL18 commented on app/templates/user.html
> +                <p>{{ user.nom }} : {{ user.nom }}</p>
C'est corrigé

2023-11-09 09:35 UTC, LouisL18 commented on app/templates/baseUser.html
C'est bon aussi

2023-11-09 09:51 UTC, Nathan-Etave approved these changes
Ok pour moi, ça va.

2023-11-09 10:11 UTC, RomainMechain approved these changes
C'est bon pour moi, les modifications me semblent correcte, je valide le merge.

2023-11-09 10:11 UTC, merged