Feat/administrateur accueil
Nathan-Etave/PinPon45 pull request #71
Opened 2023-12-19 16:02 UTC by ArthurVillette

-css adminstrateur 
-html administrateur

2023-12-19 18:23 UTC, Nathan-Etave requested changes
Mauvais nom de fichier (administrateur.html -> administration.html ?)

2023-12-19 18:23 UTC, Nathan-Etave commented on app/templates/administrateur.html
> +           <a class="gestion" href="{{url_for('editCategorie')}}">
editCategorie -> edit_category

2023-12-20 08:25 UTC, Nathan-Etave approved these changes
:+1:

2023-12-20 08:53 UTC, RomainMechain approved these changes
La page me semble bien, je valide la merge request.

2023-12-20 09:12 UTC, Norikokonut approved these changes
:+1:

2023-12-20 09:12 UTC, merged